kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-reader-app
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["php-app-secret"]
    verbs: ["get"]

---
# role binding for DB secret

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: application-secret
subjects:
  - kind: ServiceAccount
    name: php-app-sa
  - kind: ServiceAccount
    name: php-migrate-job 
roleRef:
  kind: Role
  name: secret-reader-app
  apiGroup: rbac.authorization.k8s.io
