apiVersion: v1
kind: Secret
metadata:
  name: php-app-secret
type: Opaque
data:
  APP_SECRET: c29tZV9zZWN1cmVfc3RyaW5n
  DATABASE_URL: cG9zdGdyZXNxbDovL2FwcDpzZWNyZXRAcG9zdGdyZXMuZGVtby1hcHAuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9hcHA= # base64

