# role for db secret

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-reader-db
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-secret"]
    verbs: ["get"]

---
# role binding for DB secret

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-postgres-secret
subjects:
  - kind: ServiceAccount
    name: php-db-sa
roleRef:
  kind: Role
  name: secret-reader-db
  apiGroup: rbac.authorization.k8s.io
