# create a service account for deployment:
apiVersion: v1
kind: ServiceAccount
metadata:
  name: php-app-sa

---
# create a deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      serviceAccountName: php-app-sa
      initContainers:
        - name: wait-for-job
          image: bitnami/kubectl:latest 
          command:
          - sh
          - -c
          - >
            until kubectl get job php-migrate-job -n "$POD_NAMESPACE" -o jsonpath="{.status.succeeded}" | grep -m 1 "1";
            do
            echo waiting for job to complete;
            sleep 10;
            done
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

      containers:
        - name: php-app
          image: mhkabir/symfony-demo:v5
          ports:
            - containerPort: 8000
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: php-app-secret
                  key: APP_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: php-app-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "100m"      # Minimum CPU required
              memory: "128Mi"  # Minimum Memory required
            limits:
              cpu: "500m"      # Maximum CPU allowed
              memory: "256Mi"  # Maximum Memory allowed
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
